version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      github-actions-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: pip
    directory: /tools
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      pip-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      npm-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
    groups:
      docker-minor-patch:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
